project:
  type: website
  output-dir: _site

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: myGraph.qmd
        text: myGraph

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



